@startuml
abstract class ConvertBase {
    # Success : string <<get>>
    # FileCheck(filePath:string) : bool
    + FilePath : string <<get>> <<init>>
    + <<virtual>> Convert() : void
}
class "Func`2"<T1,T2> {
}
class "Func`3"<T1,T2,T3> {
}
IConverter <|-- ConvertBase
ConvertBase --> "ShowMessage<string,DialogResult>" "Func`2"
ConvertBase --> "ChangeExtension<string,string,string>" "Func`3"
@enduml
